digitraceslab/niimpy

niimpy/test_survey.py

- https://travis-ci.org/CxAalto/niimpy/jobs/643853591
```
def test_sum_survey_scores_indexonly():
df = df1.copy()
>       del df.index.name
E       AttributeError: can't delete attribute
```

Fix a bug possibly with pandas 1.0.0: AttributeError: can't delete attribute

---

niimpy/database.py
niimpy/test_basic.py

- This allows one to validate usernames and present a useful error
message regardless of if the database is a singleuser db or
multiuser.
- @AnaTomomi, can you check for correctness and merge if so?

Add validate_username function

---

requirements-dev.txt

- This seems more useful for editable

requirements-dev: install package as editable

---

niimpy/__init__.py
niimpy/read.py
niimpy/test_read_sql.py

added read.py which will contain the reading functions from non-database method

added read.py

---

docs/User_Stories.md

Add some detail to the user stories

A bit of work on the user stories

---

niimpy/database.py

- Review: general check, can continue to be improved later.

niimpy/database: Update or add docstrings to many functions

---

.github/workflows/docs.yml
docs/architecture.rst
docs/index.rst
docs/schema.rst

- Schema lists standard data columns and formats
- Architecture lists the various preprocessing layers, to guide making
functions.

docs: add schema and architucture pages

---

niimpy/read.py
niimpy/test_read_csv.py
niimpy/util.py

- The read_csv function missed some important setup, which was
managing the datetimes and converting them as needed.  This adds
that to the read_csv function.
- Also add a test for this.
- Review: general check

read_csv: Do setup related to timestamps/datetimes

---

.github/workflows/install.yml
.gitignore
MANIFEST.in
niimpy/__init__.py
niimpy/_version.py
setup.py

- Improve setup.py to be similar to my other projects.  This is the
first step to making it more pip-installable (I think it may already
be but hopefully this makes it a little bit more so).
- Add a test of installation
- Local installation is not currently documented
- Review: general check

Improve setup.py for local installation

---

.gitattributes
README.md
requirements-dev.txt

- Hints on setup
- Hints on doc building
- jupyternotebook diff and merging
- put sphinx_rtd_theme first to solve compatibility problem with
docutils 0.17

Add some dev instructions

---

niimpy/preprocess.py

This is the start of a conversion process from the database-based method to dataframe-based methods:
- Previously, all of these functions took a database object and
converted them to a dataframe.  Now, the user should read data
directly into a DataFrame object, and this DataFrame is passed to
the various functions.
- Only two functions have been processed so far.
- Also extract out the data-range logic into a new function,
niimpy.preprocess.date_range.  This reduces duplication across all
of the functions in this module.
- Do some various clean-up in the functions.

niimpy/preprocess: Convert several functions to use DataFrames

---

docs/index.rst

- Adjust the main outline in preparation for filling out each page

docs/index: Create a better documentation outline

---

niimpy/__init__.py
niimpy/read.py
niimpy/test_read_sqlite.py

- Add a function to list tables in a database, which is probably quite
useful but is part of the database interface which is no longer
going to be advertised.
- Review: general check

niimpy.read_sqlite_tables: add function to list tables

---

niimpy/preprocess.py
niimpy/survey.py

- This is the start of looking at preprocess.py and figuring out what
to do with each function.  Document this within comments.
- Review: general check, no action needed

Add some TODOs in preprocessing files

---

niimpy/preprocess.py
niimpy/read.py

- More clear name suggested in review
- Improve documentation

Rename _read_sqlite_auto to _get_dataframe

---

niimpy/preprocess.py
niimpy/sampledata/test_battery_1.csv
niimpy/test_screen.py

- Make function accept dataframe/database
- Slightly clean up code
- Add tests
- Review: general check / does CI pass?

preprocess: screen_off: improve function to current standards

---

docs/adding-features.ipynb
docs/api/niimpy.rst
docs/api/niimpy.screen.rst
docs/index.rst
docs/screen.ipynb
niimpy/__init__.py
niimpy/preprocess.py
niimpy/read.py
niimpy/screen.py
niimpy/test_screen.py

- Move screen sensors to niimpy.screen (they have previously been
refactored and tested, tests in niimpy.test_screen)
- Import these names into both niimpy (the current place it should
be found) and niimpy.preprocess (for backwards compatibility)
- Add documentation of screen sensors

Move screen sensors to separate submodule

---

.gitignore
niimpy/EDA/EDA_missingness.py
niimpy/EDA/setup_dataframe.py
niimpy/EDA/test_EDA_missingness.py

Included basic plots + tests for data missingness and a mock dataframe for missing data.

Missingness basic plots and tests

---

niimpy/preprocess.py
niimpy/screen.py
niimpy/test_screen.py

- remove Data1 support
- Make shutdown calculation optional
- Make apply to other types of dataframes

Improve screen.screen_off some

---

niimpy/EDA/EDA_categorical.py
niimpy/EDA/test_EDA_categorical.py

Split the summary function in EDA/EDA_categorical.py into functionally separate parts.
- different functions for grouped and not grouped plots
- different functions for filtering and categorising and for plotting

Split eda categorical

---

niimpy/survey.py

Mappers for questions and answers: raw question to id, raw answer to numerical value.

Update survey module with mapping functions

---

niimpy/location.py

Two functions are defined in `location.py`:
1. `bin_location`: bin locations according to the given bin width.
2. `extract_total_distance`: extract total distance traveled for each user. 
TODO:

Add binning functionality and compute distances for location

---

niimpy/test_util.py
niimpy/util.py

Test for this function is in progress

Add aggregate function

---

niimpy/preprocessing/battery.py

Create the preprocessing folder. 
Then, add the battery.py file where the function shutdown_info is ready for review.

ADD: shutdown_info function, source:battery

---

docs/conf.py
niimpy/preprocessing/test_screen.py

Enabled jupyter notebooks on readthedocs

Example notebooks

---

docs/demo_notebooks/Exploration.ipynb

Tried different plotly renderers, but the figures are still not visible in ReadTheDocs.

Removed renderer from plots

---

docs/api/niimpy.exploration.EDA_categorical.rst
docs/api/niimpy.exploration.EDA_countplot.rst
docs/api/niimpy.exploration.EDA_missingness.rst
docs/api/niimpy.exploration.EDA_punchcard.rst
docs/api/niimpy.exploration.eda.categorical.rst
docs/api/niimpy.exploration.eda.countplot.rst
docs/api/niimpy.exploration.eda.lineplot.rst
docs/api/niimpy.exploration.eda.missingness.rst
docs/api/niimpy.exploration.eda.punchcard.rst
docs/api/niimpy.exploration.eda.rst
docs/api/niimpy.exploration.rst
docs/api/niimpy.preprocessing.aalto.rst
docs/api/niimpy.preprocessing.rst

- There was one custom modification in the main modules.rst file, I
preserved this.

Update apidocs by `cd docs ; make apidoc` and committing

---

docs/input-formats.ipynb
niimpy/reading/read.py

- Related to #81, maybe closes it (is this enough for now?)

docs/input-formats: Add some brief words about how to add more readers

---

niimpy/preprocessing/battery.py

Merging extra functions for battery processing

add new battery functions

---

niimpy/exploration/missingness.py
niimpy/preprocessing/battery.py
niimpy/preprocessing/filter.py
niimpy/preprocessing/subject_selection.py
niimpy/preprocessing/util.py
tests/preprocessing/test_filter.py

Addressing issue #64. Range limits standardized to [start,end].

Standardize interval begin -> start

---

niimpy/preprocessing/battery.py
tests/preprocessing/test_battery.py

Unify battery functions so that they follow the same input and output standard.
Review: does this break any workflows

Jarno battery streamline

---

docs/demo_notebooks/location.ipynb
niimpy/preprocessing/application.py
niimpy/preprocessing/audio.py
niimpy/preprocessing/battery.py
niimpy/preprocessing/communication.py
niimpy/preprocessing/location.py
niimpy/preprocessing/screen.py
niimpy/preprocessing/survey.py
niimpy/preprocessing/tracker.py

This is the last change for issue #281, that simplifies and unifies the user interface.
Since feature_functions was changed to features in wrapper functions (and config in feature functions), changing ALL_FEATURE_FUNCTIONS to ALL_FEATURES makes the UI clearer.

ALL_FEATURE_FUNCTIONS -> ALL_FEATURES

---

.github/workflows/codecov.yml
.github/workflows/docs.yml
.github/workflows/install.yml
.github/workflows/test.yml

Remove support for 3.7
Add 3.10

Increment supported Python version

---

niimpy/reading/mhealth.py
tests/reading/test_read_mhealth.py

Use turn number and unit columns into pandas TimeDelta columns

Unify duration formatting in mhealth data

---

niimpy/preprocessing/tracker.py
tests/preprocessing/test_tracker.py

Should assume user column and timestamp index. Should return timestamp indexed array.

Fix tracker daily step distribution

---

README.md
docs/quick-start.ipynb
docs/user_guide/Exploration.ipynb

Update URLs to point to the current documentation

Update some URLs
